### ISSUE TITLE
Invalid Line...

### ISSUE THREAD

**Issue by duerrp** [raboof/zshprof#1]
Thanks for providing this tool, it looks really useful. Unfortunately, however, the parser seems to fail on the first line of my log:

```
File "ZshXtraceToCallgrind.ml", line 111, characters 4-382:
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
[]
Fatal error: exception ZshXtraceToCallgrind.InvalidLine("\      1452762843    %6.       /home/peter/.zshrc      10      /home/peter/.zshrc              ZSH=/home/peter/.oh-my-zsh ")
```

Without looking at the code, I have no idea what the problem could be...

**Comment by raboof** [comment]
Thanks for your feedback!

It seems your `PS4` does not include the nanoseconds part of the timestamp (`%D{%6.}`).

What version of zsh are you using? Perhaps this was introduced recently? (the manpage mentions "if the system supports  the  POSIX  gettimeofday", but I'd say most systems do)

**Comment by raboof** [comment]
This should be easy to recognize, so we should probably provide a better error message in this case.

**Comment by duerrp** [comment]
Thanks for the quick response, seems I am using a fairly old zsh...

```
zsh --version                                
zsh 5.0.2 (x86_64-pc-linux-gnu)
```

**Comment by duerrp** [comment]
The slightly newer `zsh 5.0.5 (x86_64-pc-linux-gnu)` also failed with the same error. I guess I have to install from source... Anyway, closing this for now. Thanks for your help!

**Comment by raboof** [comment]
FWIW, I'm on 5.2.

I'm reopening this issue, because I think the script should provide a better error message.
