### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by zmitchell** [raboof/zshprof#2]
I know this is a pretty basic question, but I have no experience with OCaml. I did `brew install ocaml` (I'm on a Mac) and tried the command in the README, but it couldn't find the `ocamlfind` program.

**Comment by raboof** [comment]
I don't have a Mac myself, but once you find out I'd be happy to add instructions to the README!

On my system (Debian) ocamlfind is in the ocaml-findlib package, perhaps that helps?

**Comment by zmitchell** [comment]
I see, I thought it was something that came with the OCaml installation. I downloaded it via `brew install ocaml-findlib`, but now I'm getting a different error:
```
File "ZshXtraceToCallgrind.ml", line 1, characters 5-14:
Error: Unbound module Callgrind
```
It sounds like it can't find `Callgrind.ml`, but I'm running this from inside the directory that `Callgrind.ml` is in.

**Comment by dritter** [comment]
Hi. I'm not an OCAML expert here, but it looks like the other modules are not tied together properly. This code worked for me:
```zsh
ocamlfind ocamlopt -linkpkg -thread -package str ZshXtrace.ml Callgrind.ml ZshXtraceToCallgrind.ml && ./a.out < /tmp/zshstart.$$.log > zsh.callgrind
```
Note the added packages `ZshXtrace.ml` and `Callgrind.ml` here.

**Comment by OdinsHat** [comment]
@dritter you are an exceptional gentleman and a scholar. Thank you very much. You helped me fix it after a few hours!! I owe you a coffee/beer. :+1: :smile:

**Comment by raboof** [comment]
Thanks to @rage28 this is now added to the README (#3)
